### ISSUE TITLE
Send replies to inbox option?

### ISSUE THREAD

**Issue by seiyria** [bluwy/release-for-reddit-action#2]
I finally got the plugin working (thanks again!), but I noticed that replies to these posts don't go to my inbox. Is there a way to tell the action to send replies to my inbox?

**Comment by bluwy** [comment]
After further research, it seems like Reddit auto-disables notification for link posts. Comments are however enabled by default. I could add another option to enable/disable notification for both post and comment. Gonna work on it now.

**Comment by bluwy** [comment]
Done. Added a new `notification` option, which is disabled by default. You can set it to `true` to receive post and comment replies. It's updated to v1 so you don't have to change the tag.

I've tested the option at https://github.com/bluwy/release-for-reddit-action-test with manual releases and it seems to be working, no breaking changes. You can close this issue if it works for you :)

**Comment by seiyria** [comment]
Thanks a ton! I'll pre-emptively close because my project is very small and my reddit changelogs don't generally get posts, but I will definitely let you know if it isn't seeming to work!
