### ISSUE TITLE
Allow crossposting to other subreddits

### ISSUE THREAD

**Issue by thedrow** [bluwy/release-for-reddit-action#7]
It'd be nice to be able to crosspost to other relevant subreddits as well.

**Comment by bluwy** [comment]
Great idea! I can try to tackle it this weekend.

**Comment by bluwy** [comment]
This is now supported in v1.2.0. If you're using `bluwy/release-for-reddit-action@v1`, it'll be auto-updated as well.

If you provide a link to a Reddit post for the `url` option, it'll submit a crosspost instead. [Example](https://github.com/bluwy/release-for-reddit-action-test/blob/f0ff92913e453ac14b590445d60c99ede8516148/.github/workflows/release.yml#L32).

A bit verbose, but it's more flexible :)
